# Generated by Django 4.0.4 on 2022-09-23 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='clicks',
            field=models.PositiveIntegerField(default=0, verbose_name='조회수'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='likes',
            field=models.PositiveIntegerField(default=0, verbose_name='추천수'),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
