# Generated by Django 4.0.4 on 2022-09-23 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0002_cashbook_clicks_cashbook_likes_cashbook_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='title',
            field=models.CharField(default='제목을 작성해주세요.', max_length=200),
        ),
    ]
