# Generated by Django 4.0.4 on 2022-09-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0003_alter_cashbook_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cashbook',
            old_name='photo',
            new_name='image',
        ),
        migrations.AlterField(
            model_name='cashbook',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
