# Generated by Django 4.0.4 on 2022-09-25 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0016_alter_cashbook_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='title',
            field=models.CharField(error_messages={'required': '제목을 입력해주세요.'}, max_length=200),
        ),
    ]
