# Generated by Django 4.0.4 on 2022-10-01 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0020_alter_cashbook_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='content',
            field=models.TextField(),
        ),
    ]
