# Generated by Django 4.0.4 on 2022-10-01 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0024_alter_cashbook_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashbook',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime.now, editable=False, verbose_name='data published'),
        ),
    ]
