# Generated by Django 4.1.2 on 2022-10-28 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0034_comment_writer_alter_comment_comment_writer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='writer',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cashbookapp.cashbook', verbose_name='게시글 작성자'),
            preserve_default=False,
        ),
    ]
