# Generated by Django 4.1.2 on 2022-10-29 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0035_remove_comment_writer_comment_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cashbook',
            name='writer',
        ),
    ]
