# Generated by Django 4.1.2 on 2022-10-29 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashbookapp', '0037_cashbook_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment_writer',
            new_name='writer',
        ),
    ]
