# Generated by Django 4.0.4 on 2022-11-02 15:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cashbookapp', '0042_hashtag_cashbook_hashtags'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashbook',
            name='like_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cashbook',
            name='post_like',
            field=models.ManyToManyField(blank=True, related_name='like_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
